FROM golang:1.23-bookworm AS builder

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -o Acquire::Check-Valid-Until=false update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        libpcap-dev \
        libvirt-dev \
        libxml2-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /go/src/github.com/skydive-project/skydive
COPY . .

RUN go run github.com/jteeuwen/go-bindata/go-bindata \
        -nometadata \
        -o statics/bindata.go \
        -pkg=statics \
        -ignore=bindata.go \
        js/*.js \
        rbac/policy.csv \
        statics/schemas/* \
        statics/workflows/*.yaml \
        statics/ui/index.html \
        statics/ui/css/* \
        statics/ui/css/themes/*/* \
        statics/ui/fonts/* \
        statics/ui/img/* \
        statics/ui/js/* \
        statics/ui_v2/index.html \
        statics/ui_v2/assets \
        statics/ui_v2/assets/icons \
        statics/ui_v2/dist \
        statics/ui_v2/fonts \
    && gofmt -w -s statics/bindata.go

RUN CGO_CFLAGS_ALLOW='.*' CGO_LDFLAGS_ALLOW='.*' \
    go build \
        -p=1 \
        -ldflags="-X github.com/skydive-project/skydive/version.Version=0.27.0-console-20260528" \
        -tags="lxd libvirt opencontrail packetinject" \
        -o /ablestack-netdive \
        github.com/skydive-project/skydive

FROM scratch AS artifact
COPY --from=builder /ablestack-netdive /ablestack-netdive
